import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase-server';

const menu=["Home","Campaigns","Create","Content","Calendar","Prospects","Analytics"];

export default async function DashboardPage(){
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  return <main className="app-shell"><aside className="sidebar"><div className="sidebrand brand"><span className="mark">H</span>HubElites</div><nav className="menu">{menu.map((m,i)=><a className={i===0?'active':''} href="#" key={m}>{m}</a>)}</nav><div style={{position:'absolute',bottom:22,left:18,right:18}}><div className="menu"><a href="#">Brand</a><a href="#">Connections</a><a href="#">Credits</a><a href="#">Settings</a></div></div></aside><section className="workspace"><div className="topline"><div><h1>Good afternoon.</h1><p>Your Mission 1000 campaign has 5 assets ready this week.</p></div><button className="btn btn-primary">✦ Create with AI</button></div><div className="stats"><div className="stat"><strong>11</strong><span>Content ready</span></div><div className="stat"><strong>7</strong><span>Scheduled</span></div><div className="stat"><strong>4</strong><span>Published</span></div><div className="stat"><strong>83</strong><span>Funnel visits</span></div></div><div className="grid"><div className="panel"><span className="eyebrow">Next best action</span><h2 style={{fontSize:30,marginBottom:8}}>Your Wednesday video is ready.</h2><p className="sub">Coach-focused videos are currently your strongest-performing campaign format.</p><div className="flow-card" style={{marginTop:18,minHeight:210,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#0d1730,#11122d)'}}><div style={{textAlign:'center'}}><div style={{fontSize:48}}>▶</div><b>Mission 1000 — Coaches</b><div className="sub" style={{marginTop:5}}>00:34 · Vertical short</div></div></div><div style={{display:'flex',gap:10,marginTop:14}}><button className="btn btn-primary">Approve & Schedule</button><button className="btn">Edit</button></div></div><div className="panel"><h3>AI Recommendations</h3><p className="sub">What HubElites thinks you should do next.</p><div className="checklist"><div className="check"><span className="checkmark">↑</span><div><b>Create another coach campaign</b><small>4.3× more clicks than generic content.</small></div></div><div className="check"><span className="checkmark">✓</span><div><b>Complete YouTube connection</b><small>2 videos are ready to publish.</small></div></div><div className="check"><span className="checkmark">$</span><div><b>Media balance healthy</b><small>84 credits remaining.</small></div></div></div></div></div></section></main>
}
